export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_THEATER_LOGO = "GET_THEATER_LOGO";
//==============
export const GET_THEATER = "GET_THEATER";
export const GET_THEATER_CGV = "GET_THEATER_CGV";
export const GET_THEATER_CINESTAR = "GET_THEATER_CINESTAR";
export const GET_THEATER_GALAXY = "GET_THEATER_GALAXY";
export const GET_THEATER_LOTTE = "GET_THEATER_LOTTE";
export const GET_THEATER_MAGAGS = "GET_THEATER_MAGAGS";
//======================
export const GET_CINEMA_MOVIE_SHOW="GET_CINEMA_MOVIE_SHOW";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_SEAT = "GET_LIST_SEAT";
 
